### ISSUE TITLE
@exclude does not seem to work in javascript files.

### ISSUE THREAD

**Issue by surajreddy** [jsoverson/preprocess#32] opened 2014-09-04 17:55 UTC
I seem to have trouble with the @exclude parameter in javascript - the preprocessing fails with:

```javascript
// @exclude
var test = 4;
// @endexclude
var test2 = 5;
```

It seems to be getting ignored.

I'm getting this while using the library with gulp-preprocessor, see https://github.com/jas/gulp-preprocess/issues/7

**Comment by BendingBender** [comment] 2015-06-09 20:03
@surajreddy and @simkessy, can you still reproduce the problem with the latest version? I took the above example but for me everything worked fine.

**Comment by BendingBender** [comment] 2015-07-19 13:02
Closing this because author don't respond.

**Closed** 2015-07-19 13:02 UTC
Labels: bug
