### ISSUE TITLE
Can't echo strings with minus (-) sign

### ISSUE THREAD

**Issue by Juriy** [jsoverson/preprocess#45] opened 2015-01-03 12:39 UTC
Hello guys,

Have a look at the following code:
```javascript
var pp = require('preprocess');
var text = 'Hello <!-- @echo "minus-world" -->';
var out = pp.preprocess(text, {}, 'html');
console.log(out);
```
I expect it to print  
```
Hello minus-world
```

But I get back an unprocessed value
```
Hello <!-- @echo "minus-world" -->
```

If you remove the minus sign inside of an `echo` value everything's working fine.

**Comment by wardpeet** [comment] 2015-02-06 17:41
It's because of this regex "" not sure why the - is not allowed by the regex. using the following regex instead will make it work. ""

**Comment by BendingBender** [comment] 2015-06-08 20:01
Duplicate of #21.

**Comment by BendingBender** [comment] 2015-06-09 18:49
Well, atm it is possible to have multiple `@echo` rules in one line separated by multiple comment blocks like this:
```html
<!-- @echo 'hello' --><!-- @echo 'world' -->
```
The minus sign is therefore needed in the regex as a delimiter for the otherwise greedy regex search to catch exactly this case

Any ideas on how to achieve the same effect without forbidding the minus sign in echoed strings?

**Closed** 2015-06-13 05:15 UTC
Labels: duplicate, enhancement
